#!groovy

library "SharedLib@${env.BRANCH_NAME}"

pipeline {
    agent {
        label 'linux'
    }
    parameters {
        string(name: 'RELEASE_VERSION', defaultValue: '9.0.0', description: '')
        string(name: 'POST_RELEASE_SNAPSHOT_VERSION', defaultValue: '9.0.1-SNAPSHOT', description: '')
        booleanParam(name: 'BUILD_CORE', defaultValue: true, description: '')
        booleanParam(name: 'RELEASE', defaultValue: false, description: '')
    }
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }
    stages {
        stage('Prepare') {
            steps {
                cleanupWorkspaceAndCloneRepo()
                sh "git checkout ${env.BRANCH_NAME}"
                purge()
            }
        }
        stage('Build lightning-core') {
            when {
                expression {
                    "${params.BUILD_CORE}".toBoolean()
                }
            }
            steps {
                buildCore()
            }
        }
        stage('Set release version number') {
            steps {
                dir('lightning-gradle-plugin') {
                    sh "sed -i -e \"/lightningGradlePluginVersion=/ s/=.*/=${params.RELEASE_VERSION}/\" gradle.properties"
                    sh "cat gradle.properties"
                }
                sh "git add -A; git commit -m 'Lightning Gradle Plugin release version bump'"
            }
        }
        stage('Check') {
            steps {
                dir('lightning-gradle-plugin') {
                    sh './gradlew clean check --console plain'
                }
            }
            post {
                always {
                    junit 'lightning-gradle-plugin/build/test-results/integrationTest/*.xml'
                }
            }
        }
        stage('Tag release') {
            steps {
                sh "git tag gradle-plugin-${params.RELEASE_VERSION}"
            }
        }
        stage('Release') {
            when {
                expression {
                    "${params.RELEASE}".toBoolean() && "${env.BRANCH_NAME}" == "master"
                }
            }
            steps {
                dir('lightning-gradle-plugin') {
                    // Maven Central
                    sh './gradlew clean uploadArchives closeAndReleaseRepository'
                    // Gradle Plugin Portal
                    sh './gradlew clean publishPlugins'
                }
            }
        }
        stage('Set snapshot version number') {
            steps {
                dir('lightning-gradle-plugin') {
                    sh "sed -i -e \"/lightningGradlePluginVersion=/ s/=.*/=${params.POST_RELEASE_SNAPSHOT_VERSION}/\" gradle.properties"
                    sh "cat gradle.properties"
                }
                sh "git add -A; git commit -m 'Lightning Gradle Plugin post-release version bump'"
            }
        }
        stage('Push release to origin') {
            when {
                expression {
                    "${params.RELEASE}".toBoolean() && "${env.BRANCH_NAME}" == "master"
                }
            }
            steps {
                push()
            }
        }
    }
}
