os: linux
dist: trusty
language: java
install: true
jdk: openjdk8
before_cache:
  - rm -rf ~/.m2/repository/uk/co/automatictester/*lightning*/
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
jobs:
  include:
    - stage: Test
      script: ./mvnw -pl lightning-core clean verify -DmockS3
      name: "Core"
      env: CACHE=core
    - script:
        - ./mvnw -pl lightning-core clean install -DmockS3
        - ./mvnw -pl lightning-aws-lambda clean verify -DmockS3
      name: "Lambda"
      env: CACHE=lambda
    - script:
        - ./mvnw -pl lightning-core clean install -DmockS3
        - ./mvnw -pl jmeter-lightning-maven-plugin clean verify
      name: "Maven"
      env: CACHE=maven
    - script:
        - ./mvnw -pl lightning-core clean install -DmockS3
        - ./mvnw -pl lightning-standalone clean verify
      name: "Standalone"
      env: CACHE=standalone
    - script:
        - ./mvnw -pl lightning-core clean install -DmockS3
        - (cd lightning-gradle-plugin; ./gradlew clean check --console plain)
      name: "Gradle"
      env: CACHE=gradle
