#!groovy

library "SharedLib@${env.BRANCH_NAME}"

pipeline {
    agent {
        label 'linux'
    }
    parameters {
        string(name: 'RELEASE_VERSION', defaultValue: '9.0.0', description: '')
        string(name: 'POST_RELEASE_SNAPSHOT_VERSION', defaultValue: '9.0.1-SNAPSHOT', description: '')
        booleanParam(name: 'RELEASE', defaultValue: false, description: '')
    }
    options {
        timestamps()
        skipDefaultCheckout()
        disableConcurrentBuilds()
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }
    stages {
        stage('Prepare') {
            steps {
                cleanupWorkspaceAndCloneRepo()
                sh "git checkout ${env.BRANCH_NAME}"
                purge()
            }
        }
        stage('Set release version number') {
            steps {
                sh "./mvnw -pl lightning-core versions:set -DnewVersion=${params.RELEASE_VERSION} -DprocessDependencies=true"
                dir('lightning-gradle-plugin') {
                    sh "sed -i -e \"/lightningCoreVersion=/ s/=.*/=${params.RELEASE_VERSION}/\" gradle.properties"
                    sh "cat gradle.properties"
                }
                sh "git add -A; git commit -m 'Lightning Core release version bump'"
            }
        }
        stage('Verify') {
            steps {
                sh './mvnw -pl lightning-core clean verify -DmockS3'
            }
            post {
                always {
                    junit 'lightning-core/target/*-reports/junitreports/*.xml'
                    jacoco execPattern: '**/jacoco*.exec'
                }
            }
        }
        stage('Tag release') {
            steps {
                sh "git tag core-${params.RELEASE_VERSION}"
            }
        }
        stage('Release') {
            when {
                expression {
                    "${params.RELEASE}".toBoolean() && "${env.BRANCH_NAME}" == "master"
                }
            }
            steps {
                withCredentials([string(credentialsId: 'gpg-passphrase', variable: 'GPGPP')]) {
                    sh "./mvnw -pl lightning-core clean deploy -P release -DmockS3 -Dgpg.passphrase=${GPGPP} -DskipTests"
                }
            }
        }
        stage('Set snapshot version number') {
            steps {
                sh "./mvnw -pl lightning-core versions:set -DnewVersion=${params.POST_RELEASE_SNAPSHOT_VERSION} -DprocessDependencies=true"
                dir('lightning-gradle-plugin') {
                    sh "sed -i -e \"/lightningCoreVersion=/ s/=.*/=${params.POST_RELEASE_SNAPSHOT_VERSION}/\" gradle.properties"
                    sh "cat gradle.properties"
                }
                sh "git add -A; git commit -m 'Lightning Core post-release version bump'"
            }
        }
        stage('Push release to origin') {
            when {
                expression {
                    "${params.RELEASE}".toBoolean() && "${env.BRANCH_NAME}" == "master"
                }
            }
            steps {
                push()
            }
        }
    }
}
