AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  Lightning:
    Type: AWS::Serverless::Function
    Properties:
      Handler: uk.co.automatictester.lightning.lambda.LightningHandler
      CodeUri: ./../target/lightning-aws-lambda-1.0.0-SNAPSHOT.jar
      Runtime: java8
      Timeout: 30